# Generated by Django 4.1.3 on 2022-11-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_dec',
            new_name='task_decsc',
        ),
    ]
