# Generated by Django 4.1.3 on 2022-11-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_rename_task_dec_task_task_decsc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_decsc',
            new_name='task_desc',
        ),
    ]
