# Generated by Django 4.1.3 on 2022-11-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image/None/Noimg.jpg', upload_to='images/'),
        ),
    ]
